# Generated by Django 6.0.3 on 2026-03-20 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasktodomanager', '0002_completedtask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompletedTask',
        ),
    ]
