# Generated by Django 6.0.3 on 2026-03-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktodomanager', '0003_delete_completedtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('inprogress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
    ]
