# Generated by Django 6.0.3 on 2026-03-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktodomanager', '0004_alter_subtask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
    ]
